name: firestore_model
description: Read-write model objects fore Cloud Firestore backend based on mutable_model package.
version: 0.3.0
author: Alexander Ryzhov <aryzhov07@gmail.com>
homepage: https://github.com/aryzhov/flutter-firestore-model

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase: "^7.0.0"
  synchronized_lite: any
  mutable_model: any

#dev_dependencies:
#  build_runner: any
#  build_web_compilers: '>=1.0.0 <2.0.0'
#  pedantic: ^1.0.0

dependency_overrides:
  mutable_model:
    path: ../flutter-mutable-model/

